title: MCNC CNE Team
author:
  name: Chris Lovett
  email: clovett@mcnc.org
description: > # this means to ignore newlines until "show_excerpts:"
  The various posts on this page will hopefully aid the NCREN Community
  in their day-to-day work life. If you have any recommendations that
  may help the broader K-12 or higher education technology communities of
  North Carolina, please drop me an email.

show_excerpts: false # set to true to show excerpts on the homepage
header_pages:
  - pacsnips/pac-file-code.md

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  mcnc-clovett
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: christopherlovett
    # pinterest: jekyll
    youtube: MCNCvideos
    # youtube_channel: MCNCvideos
    youtube_channel_name: MCNC
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    keybase: chrislovett

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
  theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
